### ISSUE TITLE
what's the data/info.json pattern~?

### ISSUE THREAD

**Issue by jiachen0212** [mmi366127/multi-ControlNet#1]
Hello, can you write a readme? Or the format of data/info.json~ Please~

**Comment by mmi366127** [comment]
This project was created to test the possibility of adding a more specific prompt to an image condition in controlnet. For instance, I can provide 2 different pose conditions to the controlnet and give each of them a specific character to draw.

Here's an example of one item in data/info.json. One line contains one item in the json file.
````{"txt": <text prompt for diffusion model>, "pose_1_text": <additional text prompt for controlnet>, "jpg": <relative path of the image>(It does not have to be a jpg file, I just use it as a key), "pose_1": <relative path of the pose image>}````

The path is relative to the dataset folder. For example, if the image is under the ``pose`` subfolder of the dataset, the relative path would be ``./pose/image.png`` or  ``pose/image.png``. 
 
Furthermore, you can add more pairs of hint images and text for the controlnet, the output would be added to the controlnet output. To add more pose and text condition to controlnet, you  might need to modify the config file and the dataset module.


The code is a combination of https://github.com/lllyasviel/ControlNet/tree/main and https://github.com/Stability-AI/StableDiffusion. You have to include these 2 repos to run the code.

I will add a readme next week, sorry for you confusion.

**Comment by jiachen0212** [comment]
Thank you very much！

---- Replied Message ----
| From | ***@***.***> |
| Date | 07/19/2024 20:42 |
| To | mmi366127/multi-ControlNet ***@***.***> |
| Cc | Jia ***@***.***>,
Author ***@***.***> |
| Subject | Re: [mmi366127/multi-ControlNet] what's the data/info.json pattern~? (Issue #1) |

This project was created to test the possibility of adding a more specific prompt to an image condition in controlnet. For instance, I can provide 2 different pose conditions to the controlnet and give each of them a specific character to draw.

Here's an example of one item in data/info.json. One line contains one item in the json file.
{"txt": <text prompt for diffusion model>, "pose_1_text": <additional text prompt for controlnet>, "jpg": <relative path of the image>(It does not have to be a jpg file, I just use it as a key), "pose_1": <relative path of the pose image>}

The path is relative to the dataset folder. For example, if the image is under the pose subfolder of the dataset, the relative path would be ./pose/image.png or pose/image.png.

Furthermore, you can add more pairs of hint images and text for the controlnet, the output would be added to the controlnet output. To add more pose and text condition to controlnet, you might need to modify the config file and the dataset module.

The code is a combination of https://github.com/lllyasviel/ControlNet/tree/main and https://github.com/Stability-AI/StableDiffusion. You have to include these 2 repos to run the code.

I will add a readme next week, sorry for you confusion.

**Comment by jiachen0212** [comment]
> {"txt": <text prompt for diffusion model>, "pose_1_text": <additional text prompt for controlnet>, "jpg": <relative path of the image>(It does not have to be a jpg file, I just use it as a key), "pose_1": <relative path of the pose image>}

I think I understand, because I used a single control quantity to train ControlNet before, which required: source, target, prompt (https://github.com/lllyasviel/ControlNet/blob/main/docs/train.md).  Can we understand it this way, txt and pose_1_text can actually be set to the same, jpg can be considered as the target image path, pose_1 can be considered as the source image path~

**Comment by mmi366127** [comment]
The understanding regarding the target and source image is correct. The text prompt of the ControlNet is txt + pose_1_text, while the text prompt to the backbone is txt. You can refer to the code [here](https://github.com/mmi366127/multi-ControlNet/blob/be776d470b019ceccdbfd465924b673d23d9a531/data/__init__.py#L244). In the original controlnet, the prompt of the controlnet and the prompt of the backbone are the same. I made a difference in this project by sending different text prompts to the ControlNet, hoping we could embed some extra information into the ControlNet.

**Comment by jiachen0212** [comment]
> The understanding regarding the target and source image is correct. The text prompt of the ControlNet is txt + pose_1_text, while the text prompt to the backbone is txt. You can refer to the code [here](https://github.com/mmi366127/multi-ControlNet/blob/be776d470b019ceccdbfd465924b673d23d9a531/data/__init__.py#L244). In the original controlnet, the prompt of the controlnet and the prompt of the backbone are the same. I made a difference in this project by sending different text prompts to the ControlNet, hoping we could embed some extra information into the ControlNet.

Thank you very much. I have another question: I monitor depth and segmap together. Under data, I try:
```
depth info:
{"pose_1": "frame_00210.png", "jpg": "/xxxx0210.png", "pose_1_text": "The image ccc tccc."}
{"pose_1": "frame_00697.png", "jpg": "/xxxx0697.png", "pose_1_text": "The image cccc a ccc."}

seg info:   #bug
{"pose_2": "frame_00210.png", "jpg": "/xxxx0210.png", "pose_2_text": "The image shows tccc."}
{"pose_2": "frame_00697.png", "jpg": "/xxxx0697.png", "pose_2_text": "The image shows a ccc."}

```
But I encountered this bug:
![1721642329748](https://github.com/user-attachments/assets/eecb9c90-8c3e-49e2-a426-01b5bc46e33d)
So I changed it to:
```
depth info:
{"pose_1": "frame_00210.png", "jpg": "/xxxx0210.png", "pose_1_text": "The image ccc tccc."}
{"pose_1": "frame_00697.png", "jpg": "/xxxx0697.png", "pose_1_text": "The image cccc a ccc."}

seg info:   #bug
{"pose_1": "frame_00210.png", "jpg": "/xxxx0210.png", "pose_1_text": "The image shows tccc."}
{"pose_1": "frame_00697.png", "jpg": "/xxxx0697.png", "pose_1_text": "The image shows a ccc."}

```
But I see the difference between pose1 and 2 in the model config, 
```
              transformer_depth: 1
              context_dim: 768
              use_checkpoint: True
              legacy: False
        cond_keys: # the name of the control and the corresponding model
          pose_1: pose_model
          pose_2: pose_model
        image_control_keys: # the name of the control and the corresponding image condition in batch
          pose_1: pose_1
          pose_2: pose_2
        text_control_keys: # the name of the control and the corresponding text embedding in batch
          pose_1: pose_1_text
          pose_2: pose_2_text
    unet_config:
      target: cldm.cldm.ControlledUnetModel
      params:
        image_size: 32 # unused
        in_channels: 4
        out_channels: 4
```
so I am wondering if I have run the model correctly and used two controls.
